### ISSUE TITLE
Is there a way to deploy it on Heroku?

### ISSUE THREAD

**Issue by marekciupak** [fullstackreact/food-lookup-demo-rails#2]
Hi,

is there a way to deploy this on Heroku? I mean two applications (RoR and React) stored inside a one git repository exactly like here.

I assume that it may require two apps on Heroku, but that's fine. I just don't want to separate the codebase into two different repositories. I'm wondering if there is a simple way to do it.

Thanks!

**Comment by acco** [comment]
Hi @marekciupak --

We have an example of this over on the Node app. Check out [the steps](https://github.com/fullstackreact/food-lookup-demo#steps) that describe it.

For production, you can create a static bundle of your React app (called `build`). You no longer need a Webpack development server, just your Rails server.  You just need to have Rails serve the static bundle that Webpack generates (`build`).

This is the same solution we use for the Node version linked above. 

I haven't gotten around to making a Heroku demo for this repo, but if you come up with something definitely make a PR!

**Comment by acco** [comment]
Closing, feel free to open if you have questions.
