### ISSUE TITLE
Semantic UI having trouble installing

### ISSUE THREAD

**Issue by gloverab** [fullstackreact/food-lookup-demo-rails#4]
Hey there - Just wanted to write this here for anyone who was as frustrated as I was, and open it as an issue for fsr to resolve (it'll be easy for you guys, promise).

It looks like the user derekslife recently deleted his Github, leaving version 2.2.7 of the Semantic UI (which relies on derekslife's wrench-js) high and dry.

If you do a find all & replace in your text editor, you can replace all 200+ instances of "2.2.7" with "2.2.10," which completely remedies the issue and allows the project to install all of its dependencies without a hitch.

I'm sure fsr will update the repo soon, but for anyone who stumbles upon this before that happens, I hope it helps!

**Comment by AndreiMotinga** [comment]
Thanks for pointing that out @gloverab. I've changed semantic-ui version to 2.2.10 in package.json and installation succeeded.

**Comment by acco** [comment]
Thank you @AndreiMotinga and @gloverab. And thanks for your patience :)
